%YAML:1.0 # need to specify the file type at the top!


#############################
####### Pinhole Equi ########
#############################
cam0:
  T_cam_imu:
    - [0.015467594786553268, 0.00010831045075687662, -0.9998803637337648, 0.01657293522992721]
    - [0.9998312869202715, -0.009909989791245133, 0.015465762111573078, 0.019088867286178802]
    - [-0.009907129093402467, -0.999950888979646, -0.00026157588379704944, -0.011502587514828798]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0.009708002789869101, -0.01201312371337792, 0.0027550233838964967, -0.0012935485121302835]
  distortion_model: equidistant
  intrinsics: [494.13989396321807, 493.6115379630283, 733.7176394837132, 720.3692194931966]
  line_delay: 1.1811655671365743e-05
  resolution: [1472, 1440]
  rostopic: /cam0/image_raw
  timeshift_cam_imu: -0.010047019081816363

cam1:
  T_cam_imu:
    - [0.0001744935089278976, -0.006571889457246516, 0.9999783896769862, -0.01824496021342093]
    - [0.9999246149162778, -0.012275967448715563, -0.0002551621699106721, 0.01393612999606562]
    - [0.012277379058667992, 0.9999030507465017, 0.006569251958173983, -0.012881899770015652]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0.006750128555584913, -0.0077189834362255995, 0.0018182300816154307, -0.0007645192078998152]
  distortion_model: equidistant
  intrinsics: [503.1634154142867, 503.00699926146524, 735.0753557069736, 720.3611396210961]
  line_delay: 6.27810068397809e-06
  resolution: [1472, 1440]
  rostopic: /cam1/image_raw
  timeshift_cam_imu: -0.007810496116072584
