%YAML:1.0 # need to specify the file type at the top!


#############################
####### Pinhole Equi ########
#############################
cam0:
  T_cam_imu:
    - [0.017538565106728715, 0.00028626904326750635, -0.999846146556576, 0.02052394245821649]
    - [0.9998137173927399, -0.008064129276510124, 0.017535687392408406, 0.01409788177972009]
    - [-0.008057868657999734, -0.9999674434045585, -0.00042764897266889257, -0.011814695170156918]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.03442918444998219, -0.02155491263917851, 0.0031292637056308044, -0.0005356957576266091]
  distortion_model: equidistant
  intrinsics: [461.6398879418857, 459.7153043295965, 732.9460954720965, 720.5410566713475]
  resolution: [1472, 1440]
  rostopic: /cam0/image_raw
  timeshift_cam_imu: -0.006584760035932231

cam1:
  T_cam_imu:
    - [0.000745820203676667, -0.00584785929408338, 0.9999826229959694, -0.019983320822875215]
    - [0.99995016919628, -0.009950514081923684, -0.000803986215983099, 0.01461591419235818]
    - [0.009955042770065814, 0.9999333926873234, 0.005840146596115453, -0.028381061462177323]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.04694156447186486, -0.04598888193097635, 0.01197602371534633, -0.0015766998867207587]
  distortion_model: equidistant
  intrinsics: [481.0462499931464, 478.0014012062969, 735.0624904634898, 720.0949685881241]
  resolution: [1472, 1440]
  rostopic: /cam1/image_raw
  timeshift_cam_imu: -0.006546655556020702
