Camera:
  name: "Insta360 One RS 1-inch Edition Front Camera"
  setup: "monocular"
  model: "fisheye"

  fx: 493.66545219
  fy: 493.12847238
  cx: 733.76642558
  cy: 720.25472694

  k1: 0.01024039
  k2: -0.01255249
  k3: 0.00310332
  k4: -0.00137028

  fps: 30.0
  cols: 1472
  rows: 1440

  color_order: "Gray"

Preprocessing:
  min_size: 800

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

Initializer:
  scaling_factor: 5.0

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

System:
  map_format: "msgpack"
  num_grid_cols: 48
  num_grid_rows: 27
